<?php

namespace ContainerLxwXpBn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hri_SbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Hri.Sb_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Hri.Sb_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cart' => ['privates', 'App\\Cart\\Cart', 'getCartService', true],
        ], [
            'cart' => 'App\\Cart\\Cart',
        ]);
    }
}
