<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKxcvQdx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKxcvQdx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKxcvQdx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKxcvQdx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKxcvQdx\App_KernelDevDebugContainer([
    'container.build_hash' => 'KxcvQdx',
    'container.build_id' => '3c61abb6',
    'container.build_time' => 1705926762,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKxcvQdx');
